force-app/main/default/objects/Account.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>IF(
  ISPICKVAL(Type, &quot;Other&quot;),
  Loan_Amount__c + Repaid__c,
  Loan_Amount__c - Repaid__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shares__c.object
<CustomObject>
    <fields>
        <fullName>SharesCount__c</fullName>
        <label>Shares Count</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>Sangam</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Share Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sangam</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CNS_LWC_HelperClass.cls
public with sharing class CNS_LWC_HelperClass {
    @AuraEnabled(cacheable=true)
    public static Decimal getTotalActiveBalanceLoan() {
        List<Account> accounts = [SELECT Balance__c FROM Account WHERE Type != 'Other'];
        Decimal totalAmt = 0;
        for (Account acc : accounts) {
            totalAmt += acc.Balance__c != null ? acc.Balance__c : 0;
        }
        return totalAmt;
    }
    @AuraEnabled(cacheable=true)
    public static Decimal getTotalSharesCount() {
        List<Shares__C> Shares = [SELECT SharesCount__c FROM Shares__C];
        Decimal total = 0;
        for (Shares__C sha : Shares) {
            total += sha.SharesCount__c != null ? sha.SharesCount__c : 0;
        }
        return total;
    }
}