force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Advance_Deduction__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Loaned person</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Security_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Security person</description>
        <label>Security Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Security Contact)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <defaultValue>(&apos;In Progress&apos;)</defaultValue>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>InProgress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Due</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed On Time</fullName>
                </value>
                <value>
                    <fullName>Closed Early</fullName>
                </value>
                <value>
                    <fullName>Closed Late</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>IF(
  ISPICKVAL(Type, &quot;Other&quot;),
  Loan_Amount__c + Repaid__c,
  Loan_Amount__c - Repaid__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interest_Paid_A__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid_A__c</fullName>
    <label>Interest Paid</label>
    <summarizedField>Loan__c.Repay_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Loan__c.State__c</field>
        <operation>equals</operation>
        <value>Paid On Time, Paid Late</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Loan__c.Action__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan__c.Loan_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short_Loan</fullName>
                <label>Short Loan</label>
            </value>
            <value>
                <fullName>Regular Loan</fullName>
            </value>
            <value>
                <fullName>Annual Loan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Total_Shares__c</fullName>
        <label>Total Shares</label>
        <precision>18</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/DefaultRecord.cls
// ✅ Overview:
// This class creates a parent Account record named 'Total Accounts' for loan applications.
// It looks for contacts named 'ADMIN1' and 'ADMIN2' and assigns them to custom fields on the Account.
// If those contacts don’t exist, it creates them dynamically.


public with sharing class DefaultRecord {
    public static ID accountFetch(String AccountName){
        //String AccountName = 'Expenses Account';
        List<Account> AccountList = [Select Id, Loan_Amount__c,Balance__c,Interest_Paid_A__c,state__C,Type ,Type__C,Contact__c,Advance_Deduction__c from Account WHERE Name = :AccountName limit 1 ];//Id  = '0012w00001Kv7dcAAB']; 
        id AID = null;
        if(AccountList.size() == 0) {
            AID = (ID)DefaultRecord.AccountCreate(AccountName);
            //LoanC.Loan_Account__c = AID;
            AccountList = [Select Loan_Amount__c,Balance__c,Interest_Paid_A__c,state__C,Type ,Type__C,Contact__c,Advance_Deduction__c from Account WHERE ID = :AID limit 1 ];//Id  = '0012w00001Kv7dcAAB']; 
        }
        if(AccountList.size() > 0 ){
            AID = AccountList[0].Id;
            if(AccountName=='Expenses Account')
                AccountList[0].Loan_Amount__c = CNS_LWC_HelperClass.getSangamTotalExpenses(); 
            else if(AccountName=='Donation Account')
                AccountList[0].Loan_Amount__c = CNS_LWC_HelperClass.getSangamTotalDonation(); 
            else if(AccountName=='Available Balance')
                AccountList[0].Loan_Amount__c = 0 + CNS_LWC_HelperClass.getSangamTotalDonation() - CNS_LWC_HelperClass.getSangamTotalExpenses(); 
            update AccountList;
        }
        return AID;
    }
    public static ID AccountCreate(String accountName) {
        Account acc = new Account();
        acc.Name = accountName;
        acc.Type__C = 'Other';    
        acc.Type = 'Other';    
        acc.Description = 'This is a parent account';
        acc.Loan_Amount__c=0;
        List<Contact> adminContacts = [SELECT Id, Name FROM Contact WHERE Name like '%Admin%' LIMIT 2];

        Id admin1Id, admin2Id;

        for (Contact admin : adminContacts) {
            if (admin.get('Name') == 'ADMIN1') {
                admin1Id = (Id)admin.get('Id');
            } else if (admin.get('Name') == 'ADMIN2') {
                admin2Id = (Id)admin.get('Id');
            }
        }
        acc.Contact__C = admin1Id != null ? admin1Id : ContactCreate('ADMIN1');
        acc.Security_Contact__c = admin2Id != null ? admin2Id : ContactCreate('ADMIN2');

        try {
            insert acc;
            return acc.Id;
        } catch (Exception e) {
            System.debug('Error creating parent account: ' + e.getMessage());
            return null;
        }
    }
    public static Id ContactCreate(String contactName) {
        Contact newContact = new Contact();
        newContact.LastName = contactName;
        newContact.Total_Shares__c = 0;
        try {
            insert newContact;
            return newContact.Id;
        } catch (Exception e) {
            System.debug('Error creating contact: ' + e.getMessage());
            return null;
        }
    }
}