force-app/main/default/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <displayFormat>Loan-{0000}</displayFormat>
        <label>Account Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Advance_Deduction__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Loaned person</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Contact)</relationshipLabel>
        <relationshipName>Accounts1</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SLAExpirationDate__c</fullName>
        <label>Repay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SLASerialNumber__c</fullName>
        <label>SLA Serial Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SLA__c</fullName>
        <label>SLA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Gold</fullName>
                </value>
                <value>
                    <fullName>Silver</fullName>
                </value>
                <value>
                    <fullName>Platinum</fullName>
                </value>
                <value>
                    <fullName>Bronze</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Security_Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Security person</description>
        <label>Security Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts (Security Contact)</relationshipLabel>
        <relationshipName>Accounts2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <defaultValue>(&apos;In Progress&apos;)</defaultValue>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>InProgress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Due</fullName>
                </value>
                <value>
                    <fullName>Overdue</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Closed On Time</fullName>
                </value>
                <value>
                    <fullName>Closed Early</fullName>
                </value>
                <value>
                    <fullName>Closed Late</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <formula>IF(
  ISPICKVAL(Type, &quot;Other&quot;),
  Loan_Amount__c + Repaid__c,
  Loan_Amount__c - Repaid__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/Interest_Paid_A__c.field-meta.xml
<CustomField>
    <fullName>Interest_Paid_A__c</fullName>
    <label>Interest Paid</label>
    <summarizedField>Loan__c.Repay_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Loan__c.State__c</field>
        <operation>equals</operation>
        <value>Paid On Time, Paid Late</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Loan__c.Action__c</field>
        <operation>equals</operation>
        <value>Interest</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan__c.Loan_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Loan_Date__c.field-meta.xml
<CustomField>
    <fullName>Loan_Date__c</fullName>
    <defaultValue>(TODAY())</defaultValue>
    <label>Loan Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Repaid__c.field-meta.xml
<CustomField>
    <fullName>Repaid__c</fullName>
    <label>Repaid</label>
    <summarizedField>Loan__c.Repay_Amount__c</summarizedField>
    <summaryFilterItems>
        <field>Loan__c.State__c</field>
        <operation>equals</operation>
        <value>Paid On Time, Paid Late</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Loan__c.Action__c</field>
        <operation>equals</operation>
        <value>Installment, Repay</value>
    </summaryFilterItems>
    <summaryForeignKey>Loan__c.Loan_Account__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short_Loan</fullName>
                <label>Short Loan</label>
            </value>
            <value>
                <fullName>Regular Loan</fullName>
            </value>
            <value>
                <fullName>Annual Loan</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Load_Account__b/Load_Account__b.object-meta.xml
<CustomObject>
    <label>Load Account</label>
    <pluralLabel>Loan Accounts</pluralLabel>
</CustomObject>

force-app/main/default/objects/Load_Account__b/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Load_Account__b/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loan Accounts</relationshipLabel>
    <relationshipName>Loan_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Load_Account__b/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Load_Account__b/fields/Loan_Type__c.field-meta.xml
<CustomField>
    <fullName>Loan_Type__c</fullName>
    <label>Loan Type</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Load_Account__b/fields/Security_Contact__c.field-meta.xml
<CustomField>
    <fullName>Security_Contact__c</fullName>
    <label>Security Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Loan Accounts1</relationshipLabel>
    <relationshipName>Loan_Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Load_Account__b/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Flow2Apex.cls
/**
* @File Name : Flow2Apex.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : December 20, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 20, 2025 |   | Initial Version
**/

public class Flow2Apex {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
	@AuraEnabled(cacheable=true)
	public static List<Load_Account__b> getLoanData() {
		// Query Big Object (only indexed fields allowed in WHERE clause)
		List<Load_Account__b> loans = [
			SELECT Id, CreatedDate, Name__c, Contact__c, 
			Contact_Name__c, Loan_Type__c, Loan_Amount__c, 
			Account_Number__c, Details__c 
			FROM Load_Account__b
			LIMIT 50
		];
		return loans;
	}
	


	@InvocableMethod(label='ArchiveLoan')
	public static void ArchiveLoan(List<Id> loanIds){
		//ArchiveLoan related records
		//invoke a queuable job to add bigobjetct and delete the respective records
        for(Id input : loanIds) {
            // Example: fetch the record
            Account acc = [SELECT Id, MasterRecordId, Name, Type, ParentId, Phone, AccountNumber, Industry, AnnualRevenue, Ownership, Description, OwnerId, CreatedDate, AccountSource, Repaid__c, SLA__c, Active__c, Balance__c, Interest_Paid_A__c, SLASerialNumber__c, SLAExpirationDate__c, Loan_Date__c, Contact__c, Security_Contact__c, Account_Id__c, Loan_Amount__c, Advance_Deduction__c, State__c, Type__c 
			FROM Account 
			WHERE Id = :input];
            acc.Description = 'Updated via Flow → Apex';
            //update acc;
			System.debug(' Received the Account. account Details are below:');
			System.debug(acc);
			Id jobId = System.enqueueJob(new ArchiveLoanAccountQueuable(acc));
			System.debug('Job queued with Id: ' + jobId);
        }
    }
}