force-app/main/default/objects/Loan__c.object
<CustomObject>
    <fields>
        <fullName>Action__c</fullName>
        <defaultValue>(&quot;Loan&quot;)</defaultValue>
        <description>Loan or Repay or Interest</description>
        <label>Action</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Installment</fullName>
                    <default>true</default>
                    <label>Installment</label>
                </value>
                <value>
                    <fullName>Repay</fullName>
                </value>
                <value>
                    <fullName>Interest</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Repay_Date__c</fullName>
        <label>Repay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <!-- 
                Open - In General
                Due - Need to be paid in next 30 days
                OverDue - Payment Missed
                Upcoming - Due For rest of the payment (for 10 months)
                Paid On Time - Paid on time : Paid before due date
                Paid Late - Paid after due date : Paid on OverDue Status
                -->
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Due</fullName>
                </value>
                <value>
                    <fullName>OverDue</fullName>
                </value>
                <value>
                    <fullName>Upcoming</fullName>
                </value>
                <value>
                    <fullName>Paid On Time</fullName>
                </value>
                <value>
                    <fullName>Paid Late</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Repay Loan</label>
    <nameField>
        <label>Loan Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repay Loans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DailyDueChecker.cls
global class DailyDueChecker implements Schedulable {
    global void execute(SchedulableContext SC) {
        // Your logic here
        list<Loan__c> LoanCList  = [SELECT Id,  Name,   Action__c,  Repay_Date__c,  State__c  FROM loan__C where Repay_Date__c = Today AND Action__c = 'Installment'];
        for(Loan__c loan : LoanCList){
            loan.State__c = 'Due';
        }
        update LoanCList;
        System.debug('Scheduled job is running.');

    }
}